#!/bin/bash

#remove sacnm.txt if there has already had one
rm sacnm.txt     

#put all the names of SAC files into the file named by sacnm.txt
ls *.SAC >> sacnm.txt  

#a loop used to read sacfiles one by one
#we can use abbrivated form of commands in SAC :) "r $sacnm " means "read $sacnm "
while read sacnm       
do
r $sacnm
done <sacnm.txt
