#!/usr/bin/env python
import glob
import subprocess

for sacnm in glob.glob("*.SAC"):
    p = subprocess.Popen(['sac'], stdin=subprocess.PIPE)
    s = "r sacnm \n"
    s += "q \n"
    p.communicate(s.encode())
